name: build-exe

on:
  workflow_dispatch:
  release:
    types: [created] # 表示在创建新的 Release 时触发

jobs:
  generate_win_exe:
    name: Generate windows executable
    runs-on: windows-latest
    steps:
    - name: Pyinstaller build
      uses: sayyid5416/pyinstaller@v1.2.1
      with:
        spec: fixIcon.py
        requirements: requirements.txt
        upload_exe_with_name: 'fixIcon'
        options: --onefile,
    - name: Pyinstaller build V2
      uses: sayyid5416/pyinstaller@v1.2.1
      with:
        spec: FastFixIcon.py
        requirements: requirements.txt
        upload_exe_with_name: 'FastFixIcon'
        options: --onefile,
    - uses: actions/download-artifact@v3
      with:
        path: dist\out
    - name: Display structure of downloaded files
      run: dir -s
      working-directory: dist\out
    - name: Upload to release
      uses: xresloader/upload-to-github-release@v1.3.12
      with:
        file: dist\out\fixIcon;dist\out\FastFixIcon
        update_latest_release: true
        draft: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}