name: build-exe

on:
  release:
    types: [created] # 表示在创建新的 Release 时触发

jobs:
  generate_win_exe:
    name: Generate windows executable
    runs-on: windows-latest
    steps:
    - name: Pyinstaller build
      uses: sayyid5416/pyinstaller@v1
      with:
        spec: fixIcon.py
        requirements: requirements.txt
        upload_exe_with_name: 'fixIcon'
        options: --onefile,
