name: build-exe

on:
  release:
    types: [created] # 表示在创建新的 Release 时触发

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.8.10'
          spec: 'fixIcon.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'fixIcon'
          options: --onefile,
